Repository WildCodeSchool/orleans-js-0920-p2-elite-star, pull requests merged in 2020-11, with the labels that each got.

#48 Fix_Footer_Us 33
  src/Assets/espacefooter.jpg
  src/components/Footer/Footer.css
  src/components/Footer/Footer.jsx
Labels: Code reviewed

#55 S02 us articles
  package-lock.json
  package.json
  src/App.jsx
  src/Assets/32e68a29301be785e2cdc906f43b86993dbbb5cb.png
  src/Assets/star-wars-8-les-derniers-jedi-images-2-300x179@2x.jpg
  src/Assets/star-wars-8-nouvelles-images-4-247x300.jpg
  src/components/Articles/Articles.css
  src/components/Articles/Articles.jsx
  src/components/Footer/Footer.css
  src/components/Header/Header.css
  src/components/Header/Header.jsx
  src/components/Header/Logo/Logo.jsx
  src/components/Header/SearchBar/SearchBar.css
  src/components/Pages/Home/Home.css
  src/components/Pages/Home/Home.jsx
Labels: Code reviewed

#57 S02 us11 week selection
  src/App.jsx
  src/assets/Logo.png
  src/components/ModelsCode.jsx
  src/components/Pages/Home/Home.jsx
  src/components/WeekSelection/RandomText.jsx
  src/components/WeekSelection/SelectionCard.jsx
  src/components/WeekSelection/WeekSelection.css
  src/components/WeekSelection/WeekSelection.jsx
Labels: Code reviewed

#59 S02_US05_Searchbar
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/assets/partners/03c3a0d5-7525-4e91-a869-5e1f99779272_200x200.png
  src/assets/partners/19c0d64e-63f1-496a-8076-ef74fc992b25_200x200.png
  src/assets/partners/37a362fd-f99e-45e3-ac8d-bfb85bfd4c30_200x200.png
  src/assets/partners/4f3ce05a-780d-4242-904e-966445fc9907_200x200.png
  src/assets/partners/c1d73f41-c24b-4fc8-a9b5-e8af5b50af22_200x200.png
  src/assets/partners/df7a58cb-f169-4653-836e-f19c11c17c80_200x200.png
  src/components/Footer/Footer.css
  src/components/Footer/Footer.jsx
  src/components/Header/Header.css
  src/components/Header/Header.jsx
  src/components/Header/Logo/Logo.jsx
  src/components/Header/Nav/Nav.css
  src/components/Header/Nav/Nav.jsx
  src/components/Header/Search/Search.css
  src/components/Header/Search/Search.jsx
  src/components/Header/SearchBar/SearchBar.css
  src/components/Header/SearchBar/SearchBar.jsx
  src/components/ModelCard.jsx
  src/components/Models.css
  src/components/Pages/About/About.css
  src/components/Pages/About/About.jsx
  src/components/Pages/Home/Home.jsx
  src/components/Pages/Models/ModelCard/ModelCard.jsx
  src/components/Pages/Models/Models.css
  src/components/Pages/Models/Models.jsx
  src/components/Pages/Results/Results.css
  src/components/Pages/Results/Results.jsx
  src/index.jsx
Labels: conflicts

#60 S02 us19 intro
  package-lock.json
  package.json
  public/index.html
  src/App.jsx
  src/Assets/Jabba.jpg
  src/Assets/LogoMobile.png
  src/Assets/agence_futur.jpg
  src/components/Backtotop/BackToTop.css
  src/components/Header/Favorites/Favorites.jsx
  src/components/Header/Logo/Logo.css
  src/components/Pages/Home/ControlledCarousel/ControlledCarousel.css
  src/components/Pages/Home/ControlledCarousel/ControlledCarousel.jsx
  src/components/Pages/Home/Home.css
  src/components/Pages/Home/Home.jsx
Labels: Code reviewed

#61 S02 us35 partners section
  src/App.css
  src/App.jsx
  src/assets/partners/darthvader.png
  src/assets/partners/jabba.png
  src/assets/partners/jedi.png
  src/assets/partners/kyloren.png
  src/assets/partners/palpatine.png
  src/assets/partners/skywalker.png
  src/components/Articles/Articles.css
  src/components/Articles/Articles.jsx
  src/components/Footer/Footer.css
  src/components/Header/Header.css
  src/components/ModelsCode.jsx
  src/components/Pages/Home/ControlledCarousel/ControlledCarousel.css
  src/components/Pages/Home/ControlledCarousel/ControlledCarousel.jsx
  src/components/Pages/Home/Home.css
  src/components/Pages/Home/Home.jsx
  src/components/Pages/Home/Partners/Partners.jsx
  src/components/WeekSelection/WeekSelection.css
  src/components/WeekSelection/WeekSelection.jsx
Labels: Code reviewed

#80 S03 us09 filter
  src/App.css
  src/App.jsx
  src/components/Footer/Footer.css
  src/components/Footer/Footer.jsx
  src/components/Header/Nav/Nav.css
  src/components/Header/SearchBar/SearchBar.css
  src/components/Pages/Favourites/FavouritesPage.jsx
  src/components/Pages/Home/ControlledCarousel/ControlledCarousel.jsx
  src/components/Pages/Models/Models.css
  src/components/Pages/Models/Models.jsx
  src/components/Pages/Profile/Profile.jsx
  src/components/Pages/Results/Results.css
  src/components/Pages/Results/Results.jsx
  src/components/WeekSelection/SelectionCard.jsx
  src/components/WeekSelection/WeekSelection.css
  src/components/WeekSelection/WeekSelection.jsx
Labels: Code reviewed

#81 S03 us31 responsive model
  src/Assets/LogoMobile.png
  src/assets/32e68a29301be785e2cdc906f43b86993dbbb5cb.png
  src/assets/Jabba.jpg
  src/assets/LogoWhite.png
  src/assets/agence_futur.jpg
  src/assets/espacefooter.jpg
  src/assets/star-wars-8-les-derniers-jedi-images-2-300x179@2x.jpg
  src/assets/star-wars-8-nouvelles-images-4-247x300.jpg
  src/assets/th.jpeg
  src/components/Header/Header.jsx
  src/components/Pages/Models/ModelCard/ModelCard.jsx
  src/components/Pages/Models/Models.css
Labels: Code reviewed

#84 S03 us02 profile page
  package-lock.json
  package.json
  public/index.html
  src/App.css
  src/App.jsx
  src/components/Footer/Footer.css
  src/components/Header/Header.jsx
  src/components/Header/Nav/Nav.jsx
  src/components/Header/SearchBar/SearchBar.css
  src/components/Pages/Home/ControlledCarousel/ControlledCarousel.css
  src/components/Pages/Models/ModelCard/ModelCard.jsx
  src/components/Pages/Models/Models.css
  src/components/Pages/Models/Models.jsx
  src/components/Pages/Profile/Profile.css
  src/components/Pages/Profile/Profile.jsx
  src/components/Pages/Profile/ProfileDescription/ProfileDescription.jsx
  src/components/Pages/Profile/ProfileForm/ProfileForm.css
  src/components/Pages/Profile/ProfileForm/ProfileForm.jsx
  src/components/Pages/Results/Results.jsx
  src/components/WeekSelection/WeekSelection.jsx
Labels: Code reviewed

#86 S03 us24 about
  src/components/Pages/About/About.css
  src/components/Pages/About/About.jsx
Labels: corrections done

#87 Dev S03
  package-lock.json
  package.json
  public/index.html
  src/App.css
  src/App.jsx
  src/Assets/LogoMobile.png
  src/assets/32e68a29301be785e2cdc906f43b86993dbbb5cb.png
  src/assets/Jabba.jpg
  src/assets/LogoWhite.png
  src/assets/agence_futur.jpg
  src/assets/espacefooter.jpg
  src/assets/star-wars-8-les-derniers-jedi-images-2-300x179@2x.jpg
  src/assets/star-wars-8-nouvelles-images-4-247x300.jpg
  src/assets/th.jpeg
  src/components/Footer/Footer.css
  src/components/Footer/Footer.jsx
  src/components/Header/Header.jsx
  src/components/Header/Nav/Nav.css
  src/components/Header/Nav/Nav.jsx
  src/components/Header/SearchBar/SearchBar.css
  src/components/Pages/About/About.css
  src/components/Pages/About/About.jsx
  src/components/Pages/About/Faq/Faq.css
  src/components/Pages/About/Faq/Faq.jsx
  src/components/Pages/Favourites/FavouritesPage.jsx
  src/components/Pages/Home/ControlledCarousel/ControlledCarousel.css
  src/components/Pages/Home/ControlledCarousel/ControlledCarousel.jsx
  src/components/Pages/Models/ModelCard/ModelCard.jsx
  src/components/Pages/Models/Models.css
  src/components/Pages/Models/Models.jsx
  src/components/Pages/Profile/Profile.css
  src/components/Pages/Profile/Profile.jsx
  src/components/Pages/Profile/ProfileDescription/ProfileDescription.jsx
  src/components/Pages/Profile/ProfileForm/ProfileForm.css
  src/components/Pages/Profile/ProfileForm/ProfileForm.jsx
  src/components/Pages/Results/Results.css
  src/components/Pages/Results/Results.jsx
  src/components/WeekSelection/SelectionCard.jsx
  src/components/WeekSelection/WeekSelection.css
  src/components/WeekSelection/WeekSelection.jsx
Labels: Code reviewed

#100 S03 last fix
  package-lock.json
  package.json
  src/App.css
  src/components/Backtotop/BackToTop.css
  src/components/Footer/Footer.css
  src/components/Footer/Footer.jsx
  src/components/Header/Header.jsx
  src/components/Header/Logo/Logo.css
  src/components/Header/Logo/Logo.jsx
  src/components/Header/SearchBar/SearchBar.css
  src/components/Pages/About/About.css
  src/components/Pages/About/About.jsx
  src/components/Pages/About/Faq/Faq.css
  src/components/Pages/About/Faq/Faq.jsx
  src/components/Pages/Profile/Profile.css
  src/components/Pages/Profile/ProfileDescription/ProfileDescription.jsx
  src/components/Pages/Profile/ProfileForm/ProfileForm.jsx
  src/components/WeekSelection/RandomText.jsx
  src/components/WeekSelection/SelectionCard.jsx
  src/components/WeekSelection/WeekSelection.jsx
Labels: Code reviewed

#101 S04 fix navbar
  public/index.html
  public/logo.png
  src/components/Footer/Footer.css
  src/components/Header/Header.css
  src/components/Header/Header.jsx
  src/components/Header/Logo/Logo.css
  src/components/Header/Logo/Logo.jsx
  src/components/Header/Nav/Nav.css
  src/components/Header/Nav/Nav.jsx
  src/components/Header/SearchBar/SearchBar.css
  src/components/WeekSelection/WeekSelection.jsx
Labels: Code reviewed

#102 Toggle sides on models page
  package.json
  src/App.css
  src/App.jsx
  src/components/Articles/Articles.css
  src/components/Articles/Articles.jsx
  src/components/Footer/Footer.css
  src/components/Header/Nav/Nav.css
  src/components/Header/Nav/Nav.jsx
  src/components/Pages/About/About.jsx
  src/components/Pages/About/Faq/Faq.css
  src/components/Pages/Home/ControlledCarousel/ControlledCarousel.css
  src/components/Pages/Home/ControlledCarousel/ControlledCarousel.jsx
  src/components/Pages/Home/Partners/Partners.jsx
  src/components/Pages/Models/Models.jsx
  src/components/Pages/ToggleSide/ToggleSide.css
  src/components/Pages/ToggleSide/ToggleSide.jsx
  src/components/WeekSelection/WeekSelection.css
  src/components/WeekSelection/WeekSelection.jsx
Labels: Code reviewed

#103 S04 us about form
  package-lock.json
  package.json
  src/App.jsx
  src/components/Header/Nav/Nav.css
  src/components/Pages/About/About.jsx
  src/components/Pages/About/Aboutform/AboutForm.css
  src/components/Pages/About/Aboutform/AboutForm.jsx
Labels: Code reviewed

#104 S05 us20 add favourites
  public/index.html
  src/App.jsx
  src/components/Articles/Articles.jsx
  src/components/Header/Favorites/Favorites.jsx
  src/components/Header/Favourites/Favourites.css
  src/components/Header/Favourites/Favourites.jsx
  src/components/Header/Nav/Nav.jsx
  src/components/Pages/About/Aboutform/AboutForm.css
  src/components/Pages/About/Aboutform/AboutForm.jsx
  src/components/Pages/Favourites/FavouritesPage.jsx
  src/components/Pages/Models/ModelCard/ModelCard.jsx
  src/components/Pages/Models/Models.css
  src/components/Pages/Models/Models.jsx
  src/components/Pages/Profile/Profile.css
  src/components/Pages/Profile/Profile.jsx
  src/components/Pages/Profile/ProfileDescription/ProfileDescription.jsx
  src/components/Pages/Results/Results.jsx
Labels: Code reviewed

#105 Finished favourites page
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/components/Pages/Favourites/FavouritesCard/FavouritesCard.css
  src/components/Pages/Favourites/FavouritesCard/FavouritesCard.jsx
  src/components/Pages/Favourites/FavouritesPage.css
  src/components/Pages/Favourites/FavouritesPage.jsx
Labels: Code reviewed

#106 S03 us03 model review
  src/assets/saberDarkSide.png
  src/assets/saberResistance.png
  src/components/Pages/Profile/Profile.jsx
  src/components/Pages/Profile/Reviews.css
  src/components/Pages/Profile/Reviews.jsx
  src/components/WeekSelection/WeekSelection.css
Labels: Code reviewed

#107 Added interactive map on about page and organized the page
  README.md
  package-lock.json
  package.json
  src/assets/map.png
  src/components/Footer/Footer.jsx
  src/components/Pages/About/About.css
  src/components/Pages/About/About.jsx
  src/components/Pages/About/Aboutform/AboutForm.css
  src/components/Pages/About/Aboutform/AboutForm.jsx
  src/components/Pages/About/Faq/Faq.css
  src/components/Pages/About/Faq/Faq.jsx
Labels: Code reviewed

#109 S05 profile reviews integration
  src/App.css
  src/components/Pages/About/Aboutform/AboutForm.jsx
  src/components/Pages/Profile/Profile.css
  src/components/Pages/Profile/Profile.jsx
  src/components/Pages/Profile/ProfileDescription/ProfileDescription.jsx
  src/components/Pages/Profile/ProfileForm/ProfileForm.css
  src/components/Pages/Profile/ProfileForm/ProfileForm.jsx
  src/components/Pages/Profile/Reviews.css
  src/components/Pages/Profile/Reviews.jsx
Labels: Code reviewed

#110 S05 us24 fixe
  src/assets/GeorgeLucas.jpg
  src/assets/models/darthVader.jpg
  src/assets/models/jediRainbow.jpg
  src/assets/models/robots.jpg
  src/assets/models/stormTrooper.jpg
  src/components/Footer/Footer.jsx
  src/components/Pages/About/About.css
  src/components/Pages/About/About.jsx
  src/components/Pages/About/AboutIntro/AboutIntro.css
  src/components/Pages/About/AboutIntro/AboutIntro.jsx
  src/components/Pages/About/AboutText/AboutText.css
  src/components/Pages/About/AboutText/AboutText.jsx
Labels: Code reviewed

#112 S05 fix readme
  README.md
Labels: Code reviewed

#113 S05 fix responsive about
  src/components/Pages/About/About.css
  src/components/Pages/About/AboutIntro/AboutIntro.css
  src/components/Pages/About/AboutIntro/AboutIntro.jsx
  src/components/Pages/About/AboutText/AboutText.css
  src/components/Pages/About/AboutText/AboutText.jsx
  src/components/Pages/About/Faq/Faq.jsx
  src/components/Pages/Models/Models.css
Labels: Code reviewed

#114 Fixe padding about section
  src/components/Pages/About/AboutIntro/AboutIntro.css
  src/components/Pages/About/AboutText/AboutText.css
  src/components/Pages/About/Aboutform/AboutForm.css
Labels: Code reviewed

#115 Fix bug no results search bar
  src/components/Pages/Results/Results.jsx
Labels: Code reviewed

#116 Last sprint fix footer
  package-lock.json
  src/components/Footer/Footer.css
  src/components/Footer/Footer.jsx
  src/components/Pages/About/AboutIntro/AboutIntro.jsx
  src/components/Pages/About/AboutText/AboutText.jsx
Labels: Code reviewed

#117 last fixes
  src/components/Footer/Footer.jsx
  src/components/Pages/Favourites/FavouritesPage.jsx
Labels: Code reviewed

#118 Dev
  package-lock.json
  src/components/Footer/Footer.css
  src/components/Footer/Footer.jsx
  src/components/Pages/About/About.css
  src/components/Pages/About/AboutIntro/AboutIntro.css
  src/components/Pages/About/AboutIntro/AboutIntro.jsx
  src/components/Pages/About/AboutText/AboutText.css
  src/components/Pages/About/AboutText/AboutText.jsx
  src/components/Pages/About/Aboutform/AboutForm.css
  src/components/Pages/About/Faq/Faq.jsx
  src/components/Pages/Favourites/FavouritesPage.jsx
  src/components/Pages/Models/Models.css
  src/components/Pages/Results/Results.jsx
Labels: Code reviewed
