Repository WildCodeSchool/orleans-js-0920-p2-elite-star, pull requests merged in 2020-10, with the labels that each got.

#29 S01 us4 logo
  package-lock.json
  package.json
  public/index.html
  public/logo192.png
  public/logo512.png
  src/App.jsx
  src/Assets/Logo.png
  src/Assets/LogoWhite.png
  src/Assets/galaxy.jpg
  src/Assets/th.jpeg
  src/components/BackToTop/BackToTop.css
  src/components/BackToTop/BackToTop.jsx
  src/components/Header/Favorites/Favorites.css
  src/components/Header/Favorites/Favorites.jsx
  src/components/Header/Header.css
  src/components/Header/Header.jsx
  src/components/Header/Logo/Logo.css
  src/components/Header/Logo/Logo.jsx
  src/components/Header/Nav/Nav.css
  src/components/Header/Nav/Nav.jsx
  src/components/Header/Search/Search.css
  src/components/Header/Search/Search.jsx
  src/components/Pages/About/About.jsx
  src/components/Pages/Home/Home.css
  src/components/Pages/Home/Home.jsx
  src/components/Pages/Models/Models.jsx
  src/index.js
  src/index.jsx
Labels: Code reviewed

#30 init footer
  src/App.css
  src/components/Footer.css
  src/components/Footer.jsx
Labels: Code reviewed, corrections done

#31 create Models page with all the characters but route
  src/App.jsx
  src/components/ModelCard.jsx
  src/components/Models.css
  src/components/ModelsCode.jsx
  src/components/Pages/Home/Home.jsx
  src/components/Pages/Models/Models.jsx
  src/index.js
Labels: Code reviewed

#33 Fixed footer not called in app
  src/App.jsx
  src/components/Footer/Footer.css
  src/components/Footer/Footer.jsx
Labels: Code reviewed

#32 new articles
  src/App.css
  src/App.jsx
  src/components/Articles/Articles.css
  src/components/Articles/Articles.jsx
Labels: conflicts
